apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store
  namespace: default
  labels:
    app: retail-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-store
  template:
    metadata:
      labels:
        app: retail-store
    spec:
      containers:
        - name: retail-store
          image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.3.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            # Add environment variables if needed
            - name: DB_HOST
              value: "mysql.default.svc.cluster.local"
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: retail-store-db-secret
                  key: password
---
apiVersion: v1
kind: Service
metadata:
  name: retail-store
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: retail-store
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
