apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-ui
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-store-ui
  template:
    metadata:
      labels:
        app: retail-store-ui
    spec:
      containers:
        - name: retail-store-ui
          image: public.ecr.aws/aws-containers/retail-store-sample-ui:1.3.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: retail-store-postgres
            - name: DB_USER
              value: admin
            - name: DB_PASSWORD
              value: admin123
            - name: DB_NAME
              value: retailstore
            - name: REDIS_HOST
              value: retail-store-redis
            - name: RABBITMQ_HOST
              value: retail-store-rabbitmq
            - name: DYNAMODB_HOST
              value: retail-store-dynamodb
