apiVersion: v1
kind: Service
metadata:
  name: retail-store-ui
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: retail-store-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
