apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store
spec:
  replicas: 2
  selector:
    matchLabels:
      app: retail-store
  template:
    metadata:
      labels:
        app: retail-store
    spec:
      containers:
        - name: retail-store
          image: your-dockerhub-username/retail-store-sample-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: POSTGRES_HOST
              value: postgres
            - name: POSTGRES_PORT
              value: "5432"
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: DYNAMODB_HOST
              value: dynamodb-local
            - name: DYNAMODB_PORT
              value: "8000"
