apiVersion: v1
kind: Service
metadata:
  name: retail-store-ui
  labels:
    app: retail-store-ui
spec:
  type: LoadBalancer
  selector:
    app: retail-store-ui
  ports:
    - port: 80
      targetPort: 8080
