apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-dynamodb
  labels:
    app: retail-store-dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-store-dynamodb
  template:
    metadata:
      labels:
        app: retail-store-dynamodb
    spec:
      containers:
        - name: dynamodb
          image: amazon/dynamodb-local:latest
          ports:
            - containerPort: 8000
          command: ["java", "-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
---
apiVersion: v1
kind: Service
metadata:
  name: retail-store-dynamodb
spec:
  selector:
    app: retail-store-dynamodb
  ports:
    - port: 8000
      targetPort: 8000
  type: ClusterIP
