apiVersion: v1
kind: Service
metadata:
  name: retail-store-mysql
  namespace: default
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: retail-store-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-mysql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-store-mysql
  template:
    metadata:
      labels:
        app: retail-store-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root123
            - name: MYSQL_DATABASE
              value: retailstore
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
