apiVersion: v1
kind: Service
metadata:
  name: retail-store-rabbitmq
  namespace: default
spec:
  ports:
    - port: 5672
      targetPort: 5672
  selector:
    app: retail-store-rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-store-rabbitmq
  template:
    metadata:
      labels:
        app: retail-store-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
