apiVersion: apps/v1
kind: Deployment
metadata:
  name: retail-store-redis
  labels:
    app: retail-store-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: retail-store-redis
  template:
    metadata:
      labels:
        app: retail-store-redis
    spec:
      containers:
        - name: redis
          image: redis:7
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: retail-store-redis
spec:
  selector:
    app: retail-store-redis
  ports:
    - port: 6379
      targetPort: 6379
  type: ClusterIP
